# Generated by Django 2.1.1 on 2018-11-29 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('num_count', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNumDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField(default=django.utils.timezone.now, verbose_name='时间')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('object_id', models.PositiveIntegerField(verbose_name='所属类型主键编号')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='所属类型')),
            ],
        ),
    ]
